function C=alphaColorbar(ax,surface,varargin)
% This function creates a custom colorbar by using an axes object
% 
%% INPUT VARIABLES
% ax: axes handle
% 
% surface: surface handle generated by my_hist2 function
%% Parse inpur variables
narginchk(2,inf);
params=inputParser;
params.CaseSensitive=false;
params.addParameter('location','southoutside',@(x) ischar(x));
params.addParameter('w',20,@(x) isnumeric(x));
params.addParameter('clab',' ',@(x) ischar(x));
params.parse(varargin{:});

% Extract out values from parsed input
location=params.Results.location;
w=params.Results.w;
clab=params.Results.clab;

% axes colorbar
C=axes(ax.Parent);

% get range of values of the surface object
N=surface.CData;


try
    max1=surface.UserData;
catch
    max1=nanmax(N(:));
end
levels=0:max1;
levels=cat(1,levels,levels,levels);
levels_n=levels./max1;%normalize the levels

switch location
    case 'southoutside'
%         m=max([ax.TightInset(2) ax.TightInset(4)]);%margin
        [X,Y]=meshgrid(levels(1,:),[0 0.5 1]);
        surf(C,X,Y,ones(size(X)),'alphadatamapping','scaled',...
            'facealpha','flat','alphadata',levels_n,...
            'facecolor',surface.FaceColor,'cdata',levels);
        
        C.Position(3)=ax.Position(3);
        C.Units='pixels';
        C.Position(4)=w;
        C.Units=ax.Units;
        set(C,'xlim',[1 max1],'ylim',[0 1],...
            'view',[0 90],'FontName',ax.FontName,'xgrid','off',...
            'ygrid','off','zgrid','off','ytick',[],...
            'fontsize',ax.FontSize);
        xlabel(C,clab,'fontsize',ax.FontSize);
        
        C.Position(1)=ax.Position(1);
        C.Position(2)=C.TightInset(2);
        
        ax.OuterPosition(2)=ax.OuterPosition(2)+C.OuterPosition(4)+...
            C.TightInset(2)/2;
        ax.OuterPosition(4)=ax.OuterPosition(4)-C.OuterPosition(4)-...
            C.TightInset(2)/1.5;
        
end
