function overlay_axes(ax0,ax)
set(ax,'xlim',ax0.XLim,'ylim',ax0.YLim,'xtick',[],'ytick',[],...
    'position',ax0.Position,'fontname',ax0.FontName,...
    'fontsize',ax0.FontSize,'view',ax0.View,'xgrid','off','ygrid','off',...
    'ydir','normal','cameraupvector',ax0.CameraUpVector);